# -*- coding: utf-8 -*-
"""Sending_email_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ku0_WvhFvh-SSxKY2hu6nf3i5hfSfPd2
"""

import smtplib

def send_email(sender_email, sender_password, recipients, subject, body):
    try:
        smtp_server = 'smtp.gmail.com'
        smtp_port = 587

        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(sender_email, sender_password)

        message = f"Subject: {subject}\n\n{body}"

        server.sendmail(sender_email, recipients, message)
        print("Email sent successfully!")

        server.quit()

    except Exception as e:
        print(f"Error occurred while sending the email: {e}")

if __name__ == "virendrasinghharod":
    sender_email = 'virendrasinghharod31@gmail.com'
    sender_password = 'Nahi Bataonga'
    recipients = ['harodvirendrasingh45@gmail.com']
    subject = 'Test Email from Python'
    body = 'This is a test email sent using Python.'

    send_email(sender_email, sender_password, recipients, subject, body)